import GradeBestCand from "../../components/gradeBestCand";
import { Flex } from "@chakra-ui/react";
import "@fontsource/zcool-xiaowei"
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]";
import Head from 'next/head'

function Team({ resultsID }) {
    if (resultsID) {
        return ( 
            <>
                <Head>
        <title>评分系统</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
            <Flex flexDir={'column'} align={'center'} mt={20} h='92vh'>
                <GradeBestCand resultsID={resultsID} />
                </Flex>
                </>
        );
    }
}

export default Team;

export async function getServerSideProps(context) {
    const session = await unstable_getServerSession(context.req, context.res, authOptions)
    
    if (!session || session.user.role != 'Judge') {
        return {
            redirect: {
                destination: '/login',
                permanent: true,
            }
        }
    }
    const { id } = context.params
    return {
        props: {
            resultsID: id
        }
    }
}